### ISSUE TITLE
CoreTelephony/CTPrivate.h missing

### ISSUE THREAD

**Issue by dlevi309** [ProcursusTeam/netctl#1]
I haven’t been able to find any references to CTPrivate.h, do you think you could include it? As it’s required to compile

**Comment by dlevi309** [comment]
Or after actually looking at the what’s declared in Cellular.m, I think you meant to include <CoreTelephony/CTSetting.h> (from ios-reversed-headers by Cykey)

**Comment by sunflsks** [comment]
My bad, CTPrivate.h is a header I made myself to toss all the private CoreTelephony declarations into. It should be included now.
